# Seed exercise video lookup table with verified musclewiki.com URLs.
# Slug is auto-generated from the name via ExerciseVideo.slugify.

EXERCISE_VIDEOS = [
  # === BARBELL ===
  [ "Barbell Deadlift", "https://musclewiki.com/exercise/barbell-deadlift" ],
  [ "Deadlift", "https://musclewiki.com/exercise/barbell-deadlift" ],
  [ "Barbell Squat", "https://musclewiki.com/exercise/barbell-squat" ],
  [ "Back Squat", "https://musclewiki.com/exercise/barbell-squat" ],
  [ "Barbell Back Squat", "https://musclewiki.com/exercise/barbell-squat" ],
  [ "Barbell Bench Press", "https://musclewiki.com/exercise/barbell-bench-press" ],
  [ "Bench Press", "https://musclewiki.com/exercise/barbell-bench-press" ],
  [ "Barbell Incline Bench Press", "https://musclewiki.com/exercise/barbell-incline-bench-press" ],
  [ "Incline Bench Press", "https://musclewiki.com/exercise/barbell-incline-bench-press" ],
  [ "Barbell Romanian Deadlift", "https://musclewiki.com/exercise/barbell-romanian-deadlift" ],
  [ "Romanian Deadlift", "https://musclewiki.com/exercise/barbell-romanian-deadlift" ],
  [ "RDL", "https://musclewiki.com/exercise/barbell-romanian-deadlift" ],
  [ "Barbell Overhead Press", "https://musclewiki.com/exercise/barbell-overhead-press" ],
  [ "Overhead Press", "https://musclewiki.com/exercise/barbell-overhead-press" ],
  [ "Strict Press", "https://musclewiki.com/exercise/barbell-overhead-press" ],
  [ "Barbell Bent Over Row", "https://musclewiki.com/exercise/barbell-bent-over-row" ],
  [ "Bent Over Row", "https://musclewiki.com/exercise/barbell-bent-over-row" ],
  [ "Barbell Row", "https://musclewiki.com/exercise/barbell-bent-over-row" ],
  [ "Barbell Upright Row", "https://musclewiki.com/exercise/barbell-upright-row" ],
  [ "Barbell Front Squat", "https://musclewiki.com/exercise/barbell-front-squat-olympic" ],
  [ "Front Squat", "https://musclewiki.com/exercise/barbell-front-squat-olympic" ],
  [ "Barbell Clean And Press", "https://musclewiki.com/exercise/barbell-clean-and-press" ],
  [ "Clean And Press", "https://musclewiki.com/exercise/barbell-clean-and-press" ],
  [ "Clean and Press", "https://musclewiki.com/exercise/barbell-clean-and-press" ],
  [ "Barbell Hang Clean And Press", "https://musclewiki.com/exercise/barbell-hang-clean-and-press" ],
  [ "Hang Clean And Press", "https://musclewiki.com/exercise/barbell-hang-clean-and-press" ],
  [ "Barbell Curl", "https://musclewiki.com/exercise/barbell-curl" ],
  [ "Barbell Hip Thrust", "https://musclewiki.com/exercise/barbell-hip-thrust" ],
  [ "Hip Thrust", "https://musclewiki.com/exercise/barbell-hip-thrust" ],
  [ "Barbell Skullcrusher", "https://musclewiki.com/exercise/barbell-skullcrusher" ],
  [ "Skull Crushers", "https://musclewiki.com/exercise/barbell-skullcrusher" ],
  [ "Barbell Stiff Leg Deadlift", "https://musclewiki.com/exercise/barbell-stiff-leg-deadlifts" ],
  [ "Pendlay Row", "https://musclewiki.com/exercise/barbell-pronated-pendlay-row" ],
  [ "Barbell Pendlay Row", "https://musclewiki.com/exercise/barbell-pronated-pendlay-row" ],
  [ "Barbell Tap Pause Squat", "https://musclewiki.com/exercise/barbell-tap-pause-squat" ],
  [ "Barbell High Bar Good Morning", "https://musclewiki.com/exercise/barbell-high-bar-good-morning" ],
  [ "Good Morning", "https://musclewiki.com/exercise/barbell-high-bar-good-morning" ],
  [ "Barbell Low Bar Good Morning", "https://musclewiki.com/exercise/barbell-low-bar-good-morning" ],
  [ "Barbell Zercher Good Morning", "https://musclewiki.com/exercise/barbell-zercher-good-morning" ],
  [ "Barbell Bulgarian Split Squat", "https://musclewiki.com/exercise/barbell-bulgarian-split-squat" ],
  [ "Barbell Curtsy Lunge", "https://musclewiki.com/exercise/barbell-curtsy-lunge" ],
  [ "Barbell Snatch Grip Romanian Deadlift", "https://musclewiki.com/exercise/barbell-snatch-grip-romanian-deadlift" ],
  [ "Barbell Thruster", "https://musclewiki.com/exercise/barbell-thruster" ],
  [ "Thruster", "https://musclewiki.com/exercise/barbell-thruster" ],

  # === DUMBBELL ===
  [ "Dumbbell Bench Press", "https://musclewiki.com/exercise/dumbbell-bench-press" ],
  [ "DB Bench Press", "https://musclewiki.com/exercise/dumbbell-bench-press" ],
  [ "Dumbbell Incline Bench Press", "https://musclewiki.com/exercise/dumbbell-incline-bench-press" ],
  [ "Dumbbell Floor Press", "https://musclewiki.com/exercise/dumbbell-floor-press" ],
  [ "DB Floor Press", "https://musclewiki.com/exercise/dumbbell-floor-press" ],
  [ "Dumbbell Overhead Press", "https://musclewiki.com/exercise/dumbbell-overhead-press" ],
  [ "DB Shoulder Press", "https://musclewiki.com/exercise/dumbbell-overhead-press" ],
  [ "Dumbbell Shoulder Press", "https://musclewiki.com/exercise/dumbbell-overhead-press" ],
  [ "Dumbbell Seated Overhead Press", "https://musclewiki.com/exercise/dumbbell-seated-overhead-press" ],
  [ "Dumbbell Goblet Squat", "https://musclewiki.com/exercise/dumbbell-goblet-squat" ],
  [ "Goblet Squat", "https://musclewiki.com/exercise/dumbbell-goblet-squat" ],
  [ "DB Goblet Squat", "https://musclewiki.com/exercise/dumbbell-goblet-squat" ],
  [ "Dumbbell Romanian Deadlift", "https://musclewiki.com/exercise/dumbbell-romanian-deadlift" ],
  [ "DB Romanian Deadlift", "https://musclewiki.com/exercise/dumbbell-romanian-deadlift" ],
  [ "Dumbbell Single Arm Row", "https://musclewiki.com/exercise/dumbbell-single-arm-row" ],
  [ "Single Arm DB Row", "https://musclewiki.com/exercise/dumbbell-single-arm-row" ],
  [ "DB Row", "https://musclewiki.com/exercise/dumbbell-single-arm-row" ],
  [ "Dumbbell Row", "https://musclewiki.com/exercise/dumbbell-single-arm-row" ],
  [ "Dumbbell Lateral Raise", "https://musclewiki.com/exercise/dumbbell-lateral-raise" ],
  [ "Lateral Raise", "https://musclewiki.com/exercise/dumbbell-lateral-raise" ],
  [ "Side Raises", "https://musclewiki.com/exercise/dumbbell-lateral-raise" ],
  [ "Dumbbell Reverse Lunge", "https://musclewiki.com/exercise/dumbbell-reverse-lunge" ],
  [ "Dumbbell Thruster", "https://musclewiki.com/exercise/dumbbell-thruster" ],
  [ "DB Thruster", "https://musclewiki.com/exercise/dumbbell-thruster" ],
  [ "Dumbbell Hammer Curl", "https://musclewiki.com/exercise/dumbbell-hammer-curl" ],
  [ "Hammer Curl", "https://musclewiki.com/exercise/dumbbell-hammer-curl" ],
  [ "Dumbbell Curl", "https://musclewiki.com/exercise/dumbbell-curl" ],
  [ "Bicep Curls", "https://musclewiki.com/exercise/dumbbell-curl" ],
  [ "Dumbbell Bicep Curl", "https://musclewiki.com/exercise/dumbbell-curl" ],
  [ "Dumbbell Reverse Curl", "https://musclewiki.com/exercise/dumbbell-reverse-curl" ],
  [ "Dumbbell Twisting Curl", "https://musclewiki.com/exercise/dumbbell-twisting-curl" ],
  [ "Dumbbell Upright Row", "https://musclewiki.com/exercise/dumbbell-upright-row" ],
  [ "Dumbbell Rear Delt Row", "https://musclewiki.com/exercise/dumbbell-rear-delt-row" ],
  [ "Dumbbell Laying Reverse Fly", "https://musclewiki.com/exercise/dumbbell-laying-reverse-fly" ],
  [ "Dumbbell Reverse Fly", "https://musclewiki.com/exercise/dumbbell-laying-reverse-fly" ],
  [ "Dumbbell Overhead Tricep Extension", "https://musclewiki.com/exercise/dumbbell-overhead-tricep-extension" ],
  [ "Overhead Tricep Extension", "https://musclewiki.com/exercise/dumbbell-overhead-tricep-extension" ],
  [ "Tricep Extensions", "https://musclewiki.com/exercise/dumbbell-overhead-tricep-extension" ],
  [ "Dumbbell Bulgarian Split Squat", "https://musclewiki.com/exercise/dumbbell-bulgarian-split-squat" ],
  [ "Dumbbell Guillotine Bench Press", "https://musclewiki.com/exercise/dumbbell-guillotine-bench-press" ],
  [ "Dumbbell Goblet Good Morning", "https://musclewiki.com/exercise/dumbbell-goblet-good-morning" ],
  [ "Dumbbell Russian Twist", "https://musclewiki.com/exercise/dumbbell-russian-twist" ],
  [ "Dumbbell Alternating Reverse Lunge", "https://musclewiki.com/exercise/dumbbell-alternating-reverse-lunge" ],
  [ "Dumbbell Cross Body Romanian Deadlift", "https://musclewiki.com/exercise/dumbbell-cross-body-romanian-deadlift" ],

  # === KETTLEBELL ===
  [ "Kettlebell Swing", "https://musclewiki.com/exercise/kettlebell-swing" ],
  [ "KB Swing", "https://musclewiki.com/exercise/kettlebell-swing" ],
  [ "Kettlebell Clean And Press", "https://musclewiki.com/exercise/kettlebell-clean-and-press" ],
  [ "KB Clean and Press", "https://musclewiki.com/exercise/kettlebell-clean-and-press" ],
  [ "Kettlebell Goblet Squat", "https://musclewiki.com/exercise/kettlebell-goblet-squat" ],
  [ "Kettlebell Gorilla Row", "https://musclewiki.com/exercise/kettlebell-gorilla-row" ],
  [ "Gorilla Row", "https://musclewiki.com/exercise/kettlebell-gorilla-row" ],
  [ "Kettlebell Hang Clean And Jerk", "https://musclewiki.com/exercise/kettlebell-hang-clean-and-jerk" ],
  [ "Kettlebell Romanian Deadlift", "https://musclewiki.com/exercise/kettlebell-romanian-deadlift" ],
  [ "Kettlebell Farmers Carry", "https://musclewiki.com/exercise/kettlebell-farmers-carry" ],
  [ "Kettlebell Box Squat", "https://musclewiki.com/exercise/kettlebell-box-squat" ],
  [ "Kettlebell Single Leg Hip Thrust", "https://musclewiki.com/exercise/kettlebell-single-leg-hip-thrust" ],
  [ "Kettlebell Goblet Curl", "https://musclewiki.com/exercise/kettlebell-goblet-curl" ],
  [ "Kettlebell Situp", "https://musclewiki.com/exercise/kettlebell-situp" ],
  [ "Kettlebell Russian Twist", "https://musclewiki.com/exercise/kettlebell-russian-twist" ],
  [ "Kettlebell Assisted Bulgarian Split Squat", "https://musclewiki.com/exercise/kettlebell-assisted-bulgarian-split-squat" ],

  # === BODYWEIGHT ===
  [ "Push-up", "https://musclewiki.com/exercise/push-up" ],
  [ "Push-ups", "https://musclewiki.com/exercise/push-up" ],
  [ "Push Up", "https://musclewiki.com/exercise/push-up" ],
  [ "Press Up", "https://musclewiki.com/exercise/push-up" ],
  [ "Weighted Push Ups", "https://musclewiki.com/exercise/weighted-push-ups" ],
  [ "Pull-ups", "https://musclewiki.com/exercise/pull-ups" ],
  [ "Pull Ups", "https://musclewiki.com/exercise/pull-ups" ],
  [ "Pull Up", "https://musclewiki.com/exercise/pull-ups" ],
  [ "Chin Ups", "https://musclewiki.com/exercise/chin-ups" ],
  [ "Chin-ups", "https://musclewiki.com/exercise/chin-ups" ],
  [ "L Sit Pull Up", "https://musclewiki.com/exercise/l-sit-pull-up" ],
  [ "L Sit Chin Up", "https://musclewiki.com/exercise/l-sit-chin-up" ],
  [ "Bodyweight Squat", "https://musclewiki.com/exercise/bodyweight-squat" ],
  [ "Air Squat", "https://musclewiki.com/exercise/bodyweight-squat" ],
  [ "Air Squats", "https://musclewiki.com/exercise/bodyweight-squat" ],
  [ "Bodyweight Single Leg Squat", "https://musclewiki.com/exercise/bodyweight-single-leg-squat" ],
  [ "Pistol Squat", "https://musclewiki.com/exercise/bodyweight-single-leg-squat" ],
  [ "Pistol Squats", "https://musclewiki.com/exercise/bodyweight-single-leg-squat" ],
  [ "Bulgarian Split Squat", "https://musclewiki.com/exercise/bulgarian-split-squat" ],
  [ "Burpee", "https://musclewiki.com/exercise/burpee" ],
  [ "Burpees", "https://musclewiki.com/exercise/burpee" ],
  [ "Jump Squats", "https://musclewiki.com/exercise/jump-squats" ],
  [ "Jump Squat", "https://musclewiki.com/exercise/jump-squats" ],
  [ "Squat Jumps", "https://musclewiki.com/exercise/jump-squats" ],
  [ "Bicycle Crunch", "https://musclewiki.com/exercise/bicycle-crunch" ],
  [ "Bicycle Crunches", "https://musclewiki.com/exercise/bicycle-crunch" ],
  [ "Reverse Crunch", "https://musclewiki.com/exercise/reverse-crunch" ],
  [ "Bodyweight Russian Twist", "https://musclewiki.com/exercise/bodyweight-russian-twist" ],
  [ "Russian Twist", "https://musclewiki.com/exercise/bodyweight-russian-twist" ],
  [ "Russian Twists", "https://musclewiki.com/exercise/bodyweight-russian-twist" ],
  [ "Bodyweight Box Squat", "https://musclewiki.com/exercise/bodyweight-box-squat" ],
  [ "Bodyweight Assisted Pull Up", "https://musclewiki.com/exercise/bodyweight-assisted-pull-up" ],
  [ "Glute Bridge Eccentric Unilateral", "https://musclewiki.com/exercise/glute-bridge-eccentric-unilateral" ],
  [ "Plank", "https://musclewiki.com/exercise/plank" ],
  [ "Wall Ball", "https://musclewiki.com/exercise/wall-ball" ],
  [ "Wall Balls", "https://musclewiki.com/exercise/wall-ball" ],
  [ "In And Out Jump Squat", "https://musclewiki.com/exercise/in-and-out-jump-squat" ],
  [ "Kickbacks", "https://musclewiki.com/exercise/kickbacks" ],

  # === CABLE / MACHINE ===
  [ "Cable Rope Pushdown", "https://musclewiki.com/exercise/cable-rope-pushdown" ],
  [ "Cable Tricep Pushdown", "https://musclewiki.com/exercise/cable-rope-pushdown" ],
  [ "Tricep Pushdown", "https://musclewiki.com/exercise/cable-rope-pushdown" ],
  [ "Cable Cross Pushdown", "https://musclewiki.com/exercise/cable-cross-pushdown" ],
  [ "Cable Rope Skullcrusher", "https://musclewiki.com/exercise/cable-rope-skullcrusher" ],
  [ "Cable Pallof Press", "https://musclewiki.com/exercise/cable-pallof-press" ],
  [ "Pallof Press", "https://musclewiki.com/exercise/cable-pallof-press" ],
  [ "Machine Assisted Pull Up", "https://musclewiki.com/exercise/machine-assisted-pull-up" ],
  [ "Machine Seated Cable Row", "https://musclewiki.com/exercise/machine-seated-cable-row" ],
  [ "Seated Cable Row", "https://musclewiki.com/exercise/machine-seated-cable-row" ],
  [ "Cable Row", "https://musclewiki.com/exercise/machine-seated-cable-row" ],

  # === MEDICINE BALL ===
  [ "Medicine Ball Dead Bug", "https://musclewiki.com/exercise/medicine-ball-dead-bug" ],
  [ "Medicine Ball Lateral Lunge Slam", "https://musclewiki.com/exercise/medicine-ball-lateral-lunge-slam" ],
  [ "Plate Russian Twist", "https://musclewiki.com/exercise/plate-russian-twist" ],

  # === SPECIALTY ===
  [ "Farmers Carry", "https://musclewiki.com/exercise/kettlebell-farmers-carry" ],
  [ "Farmer's Carry", "https://musclewiki.com/exercise/kettlebell-farmers-carry" ],
  [ "Farmers Walk", "https://musclewiki.com/exercise/kettlebell-farmers-carry" ],

  # === SITUPS ===
  [ "Sit-up", "https://musclewiki.com/exercise/bodyweight-situp" ],
  [ "Sit-ups", "https://musclewiki.com/exercise/bodyweight-situp" ],
  [ "Situp", "https://musclewiki.com/exercise/bodyweight-situp" ],
  [ "Situps", "https://musclewiki.com/exercise/bodyweight-situp" ],
  [ "Weighted Sit-ups", "https://musclewiki.com/exercise/bodyweight-situp" ]
].freeze

puts "Seeding exercise videos..."
EXERCISE_VIDEOS.each do |name, url|
  slug = ExerciseVideo.slugify(name)
  ExerciseVideo.find_or_create_by!(slug: slug) do |ev|
    ev.name = name
    ev.url = url
    ev.verified = true
  end
end
puts "  → #{ExerciseVideo.count} exercise videos seeded"
